version: '3.8'

services:

  frontend:
    build: ./fe-app
    ports:
      - '3000:3000'
    container_name: fe-app
  
  backend:
    build: ./be-app
    ports:
      - '8080:8080'
    container_name: be-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_MAIL_USERNAME=${MY_EMAIL}
      - SPRING_MAIL_PASSWORD=${MY_APP_PASSWORD}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - ./be-app/src/main/resources/script/script.sql:/docker-entrypoint-initdb.d/script.sql
      - pg_data:/var/lib/postgresql/data
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pg_data: